from PyQt5 import QtCore, QtGui, QtWidgets
import patientController

class Ui_Dialog(object):
    def __init__(self):
        self.Dialog = QtWidgets.QDialog()
        self.Dialog.setObjectName("Dialog")
        self.Dialog.resize(457, 601)
        self.searchPID = QtWidgets.QLineEdit(self.Dialog)
        self.searchPID.setGeometry(QtCore.QRect(170, 30, 161, 22))
        self.searchPID.setObjectName("searchPID")
        self.label = QtWidgets.QLabel(self.Dialog)
        self.label.setGeometry(QtCore.QRect(60, 30, 121, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 90, 41, 20))
        self.label_2.setObjectName("label_2")
        self.female = QtWidgets.QRadioButton(self.Dialog)
        self.female.setGeometry(QtCore.QRect(290, 180, 95, 20))
        self.female.setObjectName("female")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(self.Dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.female)
        self.nid = QtWidgets.QLineEdit(self.Dialog)
        self.nid.setGeometry(QtCore.QRect(170, 130, 171, 22))
        self.nid.setObjectName("nid")
        self.male = QtWidgets.QRadioButton(self.Dialog)
        self.male.setGeometry(QtCore.QRect(180, 180, 95, 20))
        self.male.setObjectName("male")
        self.buttonGroup_2.addButton(self.male)
        self.label_3 = QtWidgets.QLabel(self.Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 130, 81, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 180, 51, 20))
        self.label_4.setObjectName("label_4")
        self.name = QtWidgets.QLineEdit(self.Dialog)
        self.name.setGeometry(QtCore.QRect(170, 90, 171, 22))
        self.name.setObjectName("name")
        self.edit = QtWidgets.QPushButton(self.Dialog)
        self.edit.setGeometry(QtCore.QRect(120, 550, 93, 28))
        self.edit.setObjectName("edit")
        self.cancel = QtWidgets.QPushButton(self.Dialog)
        self.cancel.setGeometry(QtCore.QRect(270, 550, 93, 28))
        self.cancel.setObjectName("cancel")
        self.label_10 = QtWidgets.QLabel(self.Dialog)
        self.label_10.setGeometry(QtCore.QRect(110, 240, 51, 20))
        self.label_10.setObjectName("label_10")
        self.unknownStatus = QtWidgets.QRadioButton(self.Dialog)
        self.unknownStatus.setGeometry(QtCore.QRect(180, 240, 81, 20))
        self.unknownStatus.setObjectName("unknownStatus")
        self.buttonGroup = QtWidgets.QButtonGroup(self.Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.unknownStatus)
        self.dischargedStatus = QtWidgets.QRadioButton(self.Dialog)
        self.dischargedStatus.setGeometry(QtCore.QRect(290, 240, 95, 20))
        self.dischargedStatus.setObjectName("dischargedStatus")
        self.buttonGroup.addButton(self.dischargedStatus)
        self.admittedStatus = QtWidgets.QRadioButton(self.Dialog)
        self.admittedStatus.setGeometry(QtCore.QRect(180, 290, 81, 20))
        self.admittedStatus.setObjectName("admittedStatus")
        self.buttonGroup.addButton(self.admittedStatus)
        self.deceasedStatus = QtWidgets.QRadioButton(self.Dialog)
        self.deceasedStatus.setGeometry(QtCore.QRect(290, 290, 95, 20))
        self.deceasedStatus.setObjectName("deceasedStatus")
        self.buttonGroup.addButton(self.deceasedStatus)
        self.label_8 = QtWidgets.QLabel(self.Dialog)
        self.label_8.setGeometry(QtCore.QRect(103, 400, 61, 20))
        self.label_8.setObjectName("label_8")
        self.phone = QtWidgets.QLineEdit(self.Dialog)
        self.phone.setGeometry(QtCore.QRect(173, 440, 171, 22))
        self.phone.setObjectName("phone")
        self.label_7 = QtWidgets.QLabel(self.Dialog)
        self.label_7.setGeometry(QtCore.QRect(113, 440, 51, 20))
        self.label_7.setObjectName("label_7")
        self.allergic = QtWidgets.QLineEdit(self.Dialog)
        self.allergic.setGeometry(QtCore.QRect(173, 400, 171, 22))
        self.allergic.setObjectName("allergic")
        self.label_9 = QtWidgets.QLabel(self.Dialog)
        self.label_9.setGeometry(QtCore.QRect(217, 370, 61, 20))
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.Dialog)
        self.line.setGeometry(QtCore.QRect(80, 380, 351, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.medhistory = QtWidgets.QLineEdit(self.Dialog)
        self.medhistory.setGeometry(QtCore.QRect(170, 480, 171, 22))
        self.medhistory.setObjectName("medhistory")
        self.label_11 = QtWidgets.QLabel(self.Dialog)
        self.label_11.setGeometry(QtCore.QRect(60, 480, 101, 20))
        self.label_11.setObjectName("label_11")
        self.line_2 = QtWidgets.QFrame(self.Dialog)
        self.line_2.setGeometry(QtCore.QRect(60, 60, 351, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.fillButton = QtWidgets.QPushButton(self.Dialog)
        self.fillButton.setGeometry(QtCore.QRect(350, 30, 93, 28))
        self.fillButton.setObjectName("fillButton")

        self.retranslateUi(self.Dialog)
        QtCore.QMetaObject.connectSlotsByName(self.Dialog)

        self.edit.clicked.connect(self.edit)
        self.cancel.clicked.connect(self.back)
        self.fillButton.clicked.connect(self.fill)        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Edit by Patient ID :"))
        self.label_2.setText(_translate("Dialog", "Name :"))
        self.female.setText(_translate("Dialog", "Female"))
        self.male.setText(_translate("Dialog", "Male"))
        self.label_3.setText(_translate("Dialog", "Personal ID :"))
        self.label_4.setText(_translate("Dialog", "Gender :"))
        self.edit.setText(_translate("Dialog", "Edit"))
        self.cancel.setText(_translate("Dialog", "Cancel"))
        self.label_10.setText(_translate("Dialog", "Status :"))
        self.unknownStatus.setText(_translate("Dialog", "Unknown"))
        self.dischargedStatus.setText(_translate("Dialog", "Discharged"))
        self.admittedStatus.setText(_translate("Dialog", "Admitted"))
        self.deceasedStatus.setText(_translate("Dialog", "Deceased"))
        self.label_8.setText(_translate("Dialog", "Allergic :"))
        self.label_7.setText(_translate("Dialog", "Phone :"))
        self.label_9.setText(_translate("Dialog", "Multivalue"))
        self.label_11.setText(_translate("Dialog", "Medical History :"))
        self.fillButton.setText(_translate("Dialog", "Fill"))


    def show(self):
        self.Dialog.show()

    def back(self):
        self.ui = patientController.Ui_Dialog()
        self.Dialog.hide()
        self.ui.show()

    def edit(self):
        patientID = self.searchPID.text()
        #TODO edit

    def fill(self):
        patientID = self.searchPID.text()
        #TODO fill data

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    sys.exit(app.exec_())
